services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-test
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
      MYSQL_DATABASE: test
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis-test
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge